steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['package', '-Dmaven.test.skip=true']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_IMAGE_PATH}:$SHORT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_IMAGE_PATH}']
images:
- '${_IMAGE_PATH}'
substitutions:
  _REPOSITORY: gke-psc-demo-repo # default value
  _IMAGE: gke-psc-image # default value
  _IMAGE_PATH: us-central1-docker.pkg.dev/gke-psc-demo/gke-psc-demo-repo/gke-psc-image # default value
